[DEFAULT]

file_read_time_tolerance = 800

filtering = True    
filterwidth = 2
# (only used if filtering = True)
bgfitorder = 2
# (only used if filtering = False)

averaginglength = 10
maxturns = 9
sidepeaks = 2
windowcenter = 50
windowwidth = 20
centerpeak_pos = automatic
    
timecolumn_name = TIME
harm1column_name = CH3
harm2column_name = CH4
lasercolumn_name = CH1
invertharm1 = False
invertharm2 = False
invertlaser = False
harm_for_auto_centerpeak = 1
turn_for_auto_centerpeak = 1
laser_threshold = 0.03
chunk_gap = 5

plot = False    
plotmax = 20
plot_all_chunks = True
plotfolder = Testplots/


[CURRENT]

maxturns = 2
averaginglength = 20
centerpeak_pos = center
file_read_time_tolerance = 20000
